name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: 'Hello world'
        run: echo "Hello $var1"
        env:
          var1: Vatsal
