name: Publish artifacts
on:
  push:
    branches: [main]

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: xyz
        env: 
          sekret: ${{secrets.SOUL_NAME}}
        run: echo $sekret
